### ISSUE TITLE
Users need over max hits notification

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS-UI#151] opened 2020-08-11 20:53 UTC
a success / failure styel message would do.

**Comment by gtasautumn** [comment] 2020-10-30 16:16
fixed by #348

**Comment by sylbakar** [comment] 2021-04-01 17:25
Tested in dev and found no indication for over max hits on Rules page:
![image](https://user-images.githubusercontent.com/49790901/113331211-a5b5ed80-92ed-11eb-8135-2f7ec9691164.png)

**Comment by tjwdev** [comment] 2021-04-01 17:41
The original ticket for this was about creating some notification for hitting over max results on a given query. It not showing up in the rules table is non-negligibly different. Will still look at and fix, but would like to distinguish this does not strictly fit under the same ticket.

**Comment by tjwdev** [comment] 2021-04-22 08:53
There might be some confusion as to what the columns represent or how they're intended to display:

For rule meta data we store whether or not a rule, as a boolean result, goes over the max allowable hits as set in the admin settings.  Currently on dev there are no rules that meet that criteria and so none display. After testing locally the mechanism for triggering an over-max-hits works, and after manually forcing a boolean true on the dev database it produced the appropriate UI result as well. (Please see attached)

If there is other expected behaviour I do not believe we've got that documented anywhere, as far as I can tell I believe this is working as intended. 

![RulesOverMaxResult](https://user-images.githubusercontent.com/20208544/115685904-ab1fba00-a326-11eb-9e8b-d723f042653c.jpg)

**Comment by sylbakar** [comment] 2021-09-02 15:31
Closing this one based on the explanation.

**Closed by sylbakar** 2021-09-02 15:31 UTC
Labels: enhancement, 4 - Done, 2.0
